/**
 * staticProblems.js
 * Banco ampliado de problemas locales — claros, bien escritos, con LaTeX correcto.
 * Ordenados de más fácil a más difícil dentro de cada tema.
 */

export const STATIC_PROBLEMS = {
  funciones: [
    // ── BÁSICOS ──
    {
      id: 'f1',
      problem: 'Dada la función $f(x) = x + 4$, calcula $f(3)$.',
      answer: '7',
      answerLatex: '7',
      steps: [
        'La función dice: toma $x$ y súmale 4.',
        'Sustituye $x = 3$: $f(3) = 3 + 4$',
        'Resultado: $f(3) = 7$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'funciones',
      topicLabel: 'Funciones',
    },
    {
      id: 'f2',
      problem: 'Dada la función $f(x) = 2x - 1$, calcula $f(5)$.',
      answer: '9',
      answerLatex: '9',
      steps: [
        'Sustituye $x = 5$: $f(5) = 2(5) - 1$',
        '$= 10 - 1$',
        'Resultado: $f(5) = 9$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'funciones',
      topicLabel: 'Funciones',
    },
    {
      id: 'f3',
      problem: 'Si $f(x) = x^2$, ¿cuánto vale $f(4)$?',
      answer: '16',
      answerLatex: '16',
      steps: [
        'La función eleva $x$ al cuadrado.',
        'Sustituye $x = 4$: $f(4) = 4^2$',
        'Resultado: $f(4) = 16$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'funciones',
      topicLabel: 'Funciones',
    },
    {
      id: 'f4',
      problem: 'Dada $f(x) = 3x + 2$, calcula $f(0)$ y $f(-1)$.',
      answer: 'f(0)=2, f(-1)=-1',
      answerLatex: 'f(0)=2,\\ f(-1)=-1',
      steps: [
        '$f(0) = 3(0) + 2 = 0 + 2 = 2$',
        '$f(-1) = 3(-1) + 2 = -3 + 2 = -1$',
        'Resultados: $f(0) = 2$ y $f(-1) = -1$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'funciones',
      topicLabel: 'Funciones',
    },
    // ── INTERMEDIOS ──
    {
      id: 'f5',
      problem: 'Dada la función $f(x) = x^2 - 3x + 2$, calcula $f(4)$.',
      answer: '6',
      answerLatex: '6',
      steps: [
        'Sustituye $x = 4$: $f(4) = 4^2 - 3(4) + 2$',
        '$= 16 - 12 + 2$',
        '$= 6$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'funciones',
      topicLabel: 'Funciones',
    },
    {
      id: 'f6',
      problem: 'Si $f(x) = 2x + 1$ y $g(x) = x^2$, calcula $g(f(2))$.',
      answer: '25',
      answerLatex: '25',
      steps: [
        'Primero calcula $f(2) = 2(2) + 1 = 5$',
        'Luego aplica $g$: $g(5) = 5^2 = 25$',
        'Resultado: $g(f(2)) = 25$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'funciones',
      topicLabel: 'Funciones',
    },
    {
      id: 'f7',
      problem: 'Dada $f(x) = \\frac{x+1}{2}$, calcula $f(7)$.',
      answer: '4',
      answerLatex: '4',
      steps: [
        'Sustituye $x = 7$: $f(7) = \\frac{7+1}{2}$',
        '$= \\frac{8}{2}$',
        '$= 4$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'funciones',
      topicLabel: 'Funciones',
    },
    {
      id: 'f8',
      problem: 'Dada $h(x) = x^3 - 4x$, calcula $h(-2)$.',
      answer: '0',
      answerLatex: '0',
      steps: [
        'Sustituye $x = -2$: $h(-2) = (-2)^3 - 4(-2)$',
        '$= -8 + 8$',
        '$= 0$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'funciones',
      topicLabel: 'Funciones',
    },
    // ── AVANZADOS ──
    {
      id: 'f9',
      problem: 'Dada $f(x) = \\frac{x+1}{x-2}$, calcula $f(0) + f(4)$.',
      answer: '2',
      answerLatex: '2',
      steps: [
        '$f(0) = \\frac{0+1}{0-2} = \\frac{1}{-2} = -\\frac{1}{2}$',
        '$f(4) = \\frac{4+1}{4-2} = \\frac{5}{2}$',
        '$f(0)+f(4) = -\\frac{1}{2}+\\frac{5}{2} = \\frac{4}{2} = 2$',
      ],
      difficulty: 'avanzado',
      type: 'open',
      topic: 'funciones',
      topicLabel: 'Funciones',
    },
    {
      id: 'f10',
      problem: 'Dada $f(x) = 3x^2 - 2x + 1$, calcula $f(2)$.',
      answer: '9',
      answerLatex: '9',
      steps: [
        'Sustituye $x = 2$: $f(2) = 3(2)^2 - 2(2) + 1$',
        'Calcula: $3(4) - 4 + 1 = 12 - 4 + 1$',
        'Resultado: $f(2) = 9$',
      ],
      difficulty: 'avanzado',
      type: 'open',
      topic: 'funciones',
      topicLabel: 'Funciones',
    },
  ],

  dominio_rango: [
    // ── BÁSICOS ──
    {
      id: 'd1',
      problem: '¿Cuál es el dominio de $f(x) = x + 5$?',
      answer: '(-inf,+inf)',
      answerLatex: '(-\\infty, +\\infty)',
      steps: [
        'Esta función es una línea recta (polinomio de grado 1).',
        'No tiene denominadores ni raíces. No hay restricciones.',
        'Dominio: todos los números reales $= (-\\infty, +\\infty)$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'dominio_rango',
      topicLabel: 'Dominio y Rango',
    },
    {
      id: 'd2',
      problem: '¿Cuál es el dominio de $f(x) = x^2 - 4$?',
      answer: '(-inf,+inf)',
      answerLatex: '(-\\infty, +\\infty)',
      steps: [
        'Es un polinomio de grado 2 (parábola).',
        'Los polinomios están definidos para cualquier $x$.',
        'Dominio $= (-\\infty, +\\infty)$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'dominio_rango',
      topicLabel: 'Dominio y Rango',
    },
    {
      id: 'd3',
      problem: 'Encuentra el dominio de $f(x) = \\frac{1}{x}$.',
      answer: '(-inf,0)U(0,+inf)',
      answerLatex: '(-\\infty,0)\\cup(0,+\\infty)',
      steps: [
        'El denominador NO puede ser cero.',
        'Pregunta: ¿para qué valor de $x$ el denominador es $0$? → $x = 0$',
        'Dominio: todos los reales excepto $x = 0$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'dominio_rango',
      topicLabel: 'Dominio y Rango',
    },
    {
      id: 'd4',
      problem: 'Encuentra el dominio de $f(x) = \\frac{1}{x - 5}$.',
      answer: '(-inf,5)U(5,+inf)',
      answerLatex: '(-\\infty, 5) \\cup (5, +\\infty)',
      steps: [
        'El denominador no puede ser cero: $x - 5 \\neq 0$',
        'Resolver: $x - 5 = 0 \\Rightarrow x = 5$',
        'Dominio: todos los reales excepto $x = 5$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'dominio_rango',
      topicLabel: 'Dominio y Rango',
    },
    {
      id: 'd5',
      problem: 'Encuentra el dominio de $g(x) = \\sqrt{x}$.',
      answer: '[0,+inf)',
      answerLatex: '[0, +\\infty)',
      steps: [
        'No se puede sacar raíz cuadrada de un número negativo.',
        'Se necesita que $x \\geq 0$.',
        'Dominio $= [0, +\\infty)$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'dominio_rango',
      topicLabel: 'Dominio y Rango',
    },
    // ── INTERMEDIOS ──
    {
      id: 'd6',
      problem: 'Encuentra el dominio de $g(x) = \\sqrt{x - 3}$.',
      answer: '[3,+inf)',
      answerLatex: '[3, +\\infty)',
      steps: [
        'El interior de la raíz debe ser $\\geq 0$.',
        '$x - 3 \\geq 0 \\Rightarrow x \\geq 3$',
        'Dominio $= [3, +\\infty)$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'dominio_rango',
      topicLabel: 'Dominio y Rango',
    },
    {
      id: 'd7',
      problem: 'Encuentra el dominio de $g(x) = \\sqrt{3x - 9}$.',
      answer: '[3,+inf)',
      answerLatex: '[3, +\\infty)',
      steps: [
        'El radicando debe ser $\\geq 0$: $3x - 9 \\geq 0$',
        'Suma 9 a ambos lados: $3x \\geq 9$',
        'Divide entre 3: $x \\geq 3$. Dominio $= [3, +\\infty)$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'dominio_rango',
      topicLabel: 'Dominio y Rango',
    },
    {
      id: 'd8',
      problem: 'Encuentra el dominio de $f(x) = \\frac{1}{x^2 - 9}$.',
      answer: '(-inf,-3)U(-3,3)U(3,+inf)',
      answerLatex: '(-\\infty,-3)\\cup(-3,3)\\cup(3,+\\infty)',
      steps: [
        'Denominador $\\neq 0$: $x^2 - 9 \\neq 0$',
        'Factoriza: $(x-3)(x+3) = 0 \\Rightarrow x = 3$ ó $x = -3$',
        'Excluir ambos valores. Dominio: todos los reales excepto $x = \\pm 3$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'dominio_rango',
      topicLabel: 'Dominio y Rango',
    },
    // ── AVANZADOS ──
    {
      id: 'd9',
      problem: 'Encuentra el dominio de $h(x) = \\frac{\\sqrt{x+4}}{x-1}$.',
      answer: '[-4,1)U(1,+inf)',
      answerLatex: '[-4, 1) \\cup (1, +\\infty)',
      steps: [
        'Condición 1 (raíz): $x + 4 \\geq 0 \\Rightarrow x \\geq -4$',
        'Condición 2 (denominador): $x - 1 \\neq 0 \\Rightarrow x \\neq 1$',
        'Combinar ambas: $[-4, 1) \\cup (1, +\\infty)$',
      ],
      difficulty: 'avanzado',
      type: 'open',
      topic: 'dominio_rango',
      topicLabel: 'Dominio y Rango',
    },
  ],

  formulas_notables: [
    // ── BÁSICOS ──
    {
      id: 'fn1',
      problem: 'Expande $(x + 3)^2$.',
      answer: 'x^2+6x+9',
      answerLatex: 'x^2 + 6x + 9',
      steps: [
        'Fórmula: $(a+b)^2 = a^2 + 2ab + b^2$',
        'Aquí $a = x$ y $b = 3$',
        '$x^2 + 2(x)(3) + 3^2 = x^2 + 6x + 9$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'formulas_notables',
      topicLabel: 'Fórmulas Notables',
    },
    {
      id: 'fn2',
      problem: 'Expande $(x + 5)^2$.',
      answer: 'x^2+10x+25',
      answerLatex: 'x^2 + 10x + 25',
      steps: [
        'Fórmula: $(a+b)^2 = a^2 + 2ab + b^2$',
        'Aquí $a = x$ y $b = 5$',
        '$x^2 + 2(x)(5) + 5^2 = x^2 + 10x + 25$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'formulas_notables',
      topicLabel: 'Fórmulas Notables',
    },
    {
      id: 'fn3',
      problem: 'Expande $(x - 4)^2$.',
      answer: 'x^2-8x+16',
      answerLatex: 'x^2 - 8x + 16',
      steps: [
        'Fórmula: $(a-b)^2 = a^2 - 2ab + b^2$',
        'Aquí $a = x$ y $b = 4$',
        '$x^2 - 2(x)(4) + 4^2 = x^2 - 8x + 16$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'formulas_notables',
      topicLabel: 'Fórmulas Notables',
    },
    {
      id: 'fn4',
      problem: 'Factoriza $x^2 - 25$. (Pista: es una diferencia de cuadrados)',
      answer: '(x+5)(x-5)',
      answerLatex: '(x+5)(x-5)',
      steps: [
        'Reconocer: $x^2 - 25 = x^2 - 5^2$',
        'Fórmula: $a^2 - b^2 = (a+b)(a-b)$',
        'Resultado: $(x+5)(x-5)$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'formulas_notables',
      topicLabel: 'Fórmulas Notables',
    },
    {
      id: 'fn5',
      problem: 'Factoriza $x^2 - 49$.',
      answer: '(x+7)(x-7)',
      answerLatex: '(x+7)(x-7)',
      steps: [
        'Reconocer diferencia de cuadrados: $x^2 - 7^2$',
        'Fórmula: $(a+b)(a-b)$',
        'Resultado: $(x+7)(x-7)$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'formulas_notables',
      topicLabel: 'Fórmulas Notables',
    },
    // ── INTERMEDIOS ──
    {
      id: 'fn6',
      problem: 'Expande $(x + 6)^2$.',
      answer: 'x^2+12x+36',
      answerLatex: 'x^2 + 12x + 36',
      steps: [
        'Fórmula: $(a+b)^2 = a^2 + 2ab + b^2$ con $a=x, b=6$',
        '$x^2 + 2(x)(6) + 6^2$',
        '$= x^2 + 12x + 36$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'formulas_notables',
      topicLabel: 'Fórmulas Notables',
    },
    {
      id: 'fn7',
      problem: 'Expande $(3x - 4)^2$.',
      answer: '9x^2-24x+16',
      answerLatex: '9x^2 - 24x + 16',
      steps: [
        'Fórmula: $(a-b)^2 = a^2 - 2ab + b^2$ con $a=3x, b=4$',
        '$(3x)^2 - 2(3x)(4) + 4^2$',
        '$= 9x^2 - 24x + 16$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'formulas_notables',
      topicLabel: 'Fórmulas Notables',
    },
    {
      id: 'fn8',
      problem: 'Factoriza $9x^2 - 16$.',
      answer: '(3x+4)(3x-4)',
      answerLatex: '(3x+4)(3x-4)',
      steps: [
        'Reconocer: $9x^2 - 16 = (3x)^2 - 4^2$',
        'Diferencia de cuadrados: $(a+b)(a-b)$',
        'Resultado: $(3x+4)(3x-4)$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'formulas_notables',
      topicLabel: 'Fórmulas Notables',
    },
    // ── AVANZADOS ──
    {
      id: 'fn9',
      problem: 'Factoriza $x^3 + 27$.',
      answer: '(x+3)(x^2-3x+9)',
      answerLatex: '(x+3)(x^2-3x+9)',
      steps: [
        'Reconocer suma de cubos: $x^3 + 3^3$',
        'Fórmula: $a^3+b^3 = (a+b)(a^2-ab+b^2)$',
        '$(x+3)(x^2 - 3x + 9)$',
      ],
      difficulty: 'avanzado',
      type: 'open',
      topic: 'formulas_notables',
      topicLabel: 'Fórmulas Notables',
    },
    {
      id: 'fn10',
      problem: 'Expande $(2x + 5)(2x - 5)$.',
      answer: '4x^2-25',
      answerLatex: '4x^2 - 25',
      steps: [
        'Reconocer: es $(a+b)(a-b)$ con $a=2x, b=5$',
        'Fórmula: $a^2 - b^2$',
        '$(2x)^2 - 5^2 = 4x^2 - 25$',
      ],
      difficulty: 'avanzado',
      type: 'open',
      topic: 'formulas_notables',
      topicLabel: 'Fórmulas Notables',
    },
  ],

  factorizacion: [
    // ── BÁSICOS ──
    {
      id: 'fac1',
      problem: 'Factoriza sacando factor común: $2x + 4$.',
      answer: '2(x+2)',
      answerLatex: '2(x+2)',
      steps: [
        '¿Qué número divide a 2 y a 4? → El MCD es 2.',
        'Saca el 2 como factor: $2(x + 2)$',
        'Verifica: $2(x+2) = 2x + 4$ ✓',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'factorizacion',
      topicLabel: 'Factorización',
    },
    {
      id: 'fac2',
      problem: 'Factoriza sacando factor común: $3x^2 + 6x$.',
      answer: '3x(x+2)',
      answerLatex: '3x(x+2)',
      steps: [
        'MCD de $3x^2$ y $6x$: el factor común es $3x$.',
        'Divide cada término: $3x^2 \\div 3x = x$ y $6x \\div 3x = 2$',
        'Resultado: $3x(x + 2)$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'factorizacion',
      topicLabel: 'Factorización',
    },
    {
      id: 'fac3',
      problem: 'Factoriza: $x^2 + 5x + 6$.',
      answer: '(x+2)(x+3)',
      answerLatex: '(x+2)(x+3)',
      steps: [
        'Busca dos números que sumen $5$ y multipliquen $6$.',
        'Los números son $2$ y $3$ (porque $2+3=5$ y $2\\times3=6$).',
        'Resultado: $(x+2)(x+3)$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'factorizacion',
      topicLabel: 'Factorización',
    },
    {
      id: 'fac4',
      problem: 'Factoriza: $x^2 - 5x + 6$.',
      answer: '(x-2)(x-3)',
      answerLatex: '(x-2)(x-3)',
      steps: [
        'Busca dos números que sumen $-5$ y multipliquen $6$.',
        'Los números son $-2$ y $-3$.',
        'Resultado: $(x-2)(x-3)$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'factorizacion',
      topicLabel: 'Factorización',
    },
    // ── INTERMEDIOS ──
    {
      id: 'fac5',
      problem: 'Factoriza completamente: $6x^3 - 9x^2 + 3x$.',
      answer: '3x(2x^2-3x+1)',
      answerLatex: '3x(2x^2 - 3x + 1)',
      steps: [
        'MCD(6, 9, 3) = 3. La variable mínima es $x$.',
        'Factor común $= 3x$',
        '$3x(2x^2 - 3x + 1)$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'factorizacion',
      topicLabel: 'Factorización',
    },
    {
      id: 'fac6',
      problem: 'Factoriza completamente: $2x^3 - 8x$.',
      answer: '2x(x+2)(x-2)',
      answerLatex: '2x(x+2)(x-2)',
      steps: [
        'Factor común: $2x(x^2 - 4)$',
        'Reconoce diferencia de cuadrados: $x^2 - 2^2$',
        'Resultado: $2x(x+2)(x-2)$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'factorizacion',
      topicLabel: 'Factorización',
    },
    {
      id: 'fac7',
      problem: 'Factoriza: $3x^2 + 12x + 12$.',
      answer: '3(x+2)^2',
      answerLatex: '3(x+2)^2',
      steps: [
        'Factor común: $3(x^2 + 4x + 4)$',
        'Reconoce cuadrado perfecto: $x^2 + 4x + 4 = (x+2)^2$',
        'Resultado: $3(x+2)^2$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'factorizacion',
      topicLabel: 'Factorización',
    },
    // ── AVANZADOS ──
    {
      id: 'fac8',
      problem: 'Factoriza: $8x^3 - 27$.',
      answer: '(2x-3)(4x^2+6x+9)',
      answerLatex: '(2x-3)(4x^2+6x+9)',
      steps: [
        'Reconocer diferencia de cubos: $(2x)^3 - 3^3$',
        'Fórmula: $a^3-b^3=(a-b)(a^2+ab+b^2)$',
        '$(2x-3)(4x^2+6x+9)$',
      ],
      difficulty: 'avanzado',
      type: 'open',
      topic: 'factorizacion',
      topicLabel: 'Factorización',
    },
  ],

  formula_general: [
    // ── BÁSICOS ──
    {
      id: 'fq1',
      problem: 'Resuelve con la fórmula general: $x^2 - 4 = 0$.',
      answer: 'x=2 o x=-2',
      answerLatex: 'x = 2 \\text{ ó } x = -2',
      steps: [
        'Identifica: $a=1,\\ b=0,\\ c=-4$',
        '$\\Delta = 0^2 - 4(1)(-4) = 0 + 16 = 16$',
        '$x = \\frac{0 \\pm \\sqrt{16}}{2} = \\frac{\\pm 4}{2}$',
        '$x_1 = 2,\\ x_2 = -2$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'formula_general',
      topicLabel: 'Fórmula General',
    },
    {
      id: 'fq2',
      problem: 'Resuelve con la fórmula general: $x^2 - 5x + 6 = 0$.',
      answer: 'x=2 o x=3',
      answerLatex: 'x = 2 \\text{ ó } x = 3',
      steps: [
        'Identifica: $a=1,\\ b=-5,\\ c=6$',
        '$\\Delta = (-5)^2 - 4(1)(6) = 25 - 24 = 1$',
        '$x = \\frac{5 \\pm \\sqrt{1}}{2} = \\frac{5 \\pm 1}{2}$',
        '$x_1 = 3,\\ x_2 = 2$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'formula_general',
      topicLabel: 'Fórmula General',
    },
    {
      id: 'fq3',
      problem: 'Resuelve: $x^2 + 2x - 8 = 0$.',
      answer: 'x=2 o x=-4',
      answerLatex: 'x = 2 \\text{ ó } x = -4',
      steps: [
        '$a=1,\\ b=2,\\ c=-8$',
        '$\\Delta = 4 + 32 = 36$',
        '$x = \\frac{-2 \\pm 6}{2}$',
        '$x_1 = \\frac{4}{2} = 2,\\ x_2 = \\frac{-8}{2} = -4$',
      ],
      difficulty: 'básico',
      type: 'open',
      topic: 'formula_general',
      topicLabel: 'Fórmula General',
    },
    // ── INTERMEDIOS ──
    {
      id: 'fq4',
      problem: 'Resuelve: $2x^2 - 4x - 6 = 0$.',
      answer: 'x=3 o x=-1',
      answerLatex: 'x = 3 \\text{ ó } x = -1',
      steps: [
        '$a=2,\\ b=-4,\\ c=-6$',
        '$\\Delta = 16 + 48 = 64$',
        '$x = \\frac{4 \\pm 8}{4}$',
        '$x_1 = 3,\\ x_2 = -1$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'formula_general',
      topicLabel: 'Fórmula General',
    },
    {
      id: 'fq5',
      problem: 'Resuelve: $x^2 - 6x + 9 = 0$.',
      answer: 'x=3',
      answerLatex: 'x = 3 \\text{ (raíz doble)}',
      steps: [
        '$a=1,\\ b=-6,\\ c=9$',
        '$\\Delta = 36 - 36 = 0$',
        'Como $\\Delta = 0$: hay una sola raíz (raíz doble).',
        '$x = \\frac{6}{2} = 3$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'formula_general',
      topicLabel: 'Fórmula General',
    },
    {
      id: 'fq6',
      problem: 'Resuelve: $3x^2 + 7x - 6 = 0$.',
      answer: 'x=2/3 o x=-3',
      answerLatex: 'x = \\frac{2}{3} \\text{ ó } x = -3',
      steps: [
        '$a=3,\\ b=7,\\ c=-6$',
        '$\\Delta = 49 + 72 = 121$',
        '$x = \\frac{-7 \\pm 11}{6}$',
        '$x_1 = \\frac{4}{6} = \\frac{2}{3},\\ x_2 = \\frac{-18}{6} = -3$',
      ],
      difficulty: 'intermedio',
      type: 'open',
      topic: 'formula_general',
      topicLabel: 'Fórmula General',
    },
    // ── AVANZADOS ──
    {
      id: 'fq7',
      problem: 'Resuelve: $x^2 + 4x + 5 = 0$.',
      answer: 'no tiene raices reales',
      answerLatex: '\\text{No tiene raíces reales } (\\Delta < 0)',
      steps: [
        '$a=1,\\ b=4,\\ c=5$',
        '$\\Delta = 16 - 20 = -4$',
        'Como $\\Delta < 0$: no existen raíces reales.',
        'Las raíces serían números complejos (fuera del curso).',
      ],
      difficulty: 'avanzado',
      type: 'open',
      topic: 'formula_general',
      topicLabel: 'Fórmula General',
    },
  ],
};

export function getRandomProblem(topicKey) {
  const pool = STATIC_PROBLEMS[topicKey];
  if (!pool || pool.length === 0) return null;
  return { ...pool[Math.floor(Math.random() * pool.length)], id: crypto.randomUUID() };
}

export function getStaticBatch(topicKey, count = 5) {
  const pool = STATIC_PROBLEMS[topicKey];
  if (!pool) return [];
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  const batch = [];
  for (let i = 0; i < count; i++) {
    batch.push({ ...shuffled[i % shuffled.length], id: crypto.randomUUID() });
  }
  return batch;
}
